### ISSUE TITLE
MMSI limit, limit

### ISSUE THREAD

**Issue by MartinElvar** [aisstream/aisstream#4]
Hello Aisstream,

First of all, thank you for providing this great api completely free of charge. 
I'm currently trying to implement your api into a project of mine, ideally i would like to show ONLY our customers vessels on a map. Now i could just add a subscription to the position report, and filter all the data out that i don't need, but you do actually provide a filter for it which is great.
However i'm a bit puzzled to why there is a limit of 50 mmsi on it? I think i'm gonna hit that limit fairly quickly which means that i have to go with the first solution and fetch everything and filter after. 
Wouldn't it make better sense for you not to send unnecesary data over the wire?

**Comment by aisstream** [comment]
We selected 50 MMSI's as a limit when first introducing the feature so that we had a upper bound on the number of MMSI's allowing us to studying the affect on this change on our system with a low value with a low expected affect. 

We are likely at a point now where we can raise it to at least a few hundred.

**Comment by MartinElvar** [comment]
Does setting a limit to the number of MMSI tax the system? I would think it would be the opposite, by providing no filters more data is transmitted.
So why have a limit at all? I'll have to consume everything then, otherwise there is a natural limit to how many vessels we can scale to.

**Comment by aisstream** [comment]
In our code base, determining if a websocket connection is subscribed to a message is synchronous where writing the message is async. Yes it would have significantly less total cpu/bandwidth cost to not write the message but we needed to ensure that increasing the total MMSI count would not have adverse affects on the synchronous portion of our broadcast code. 

We have increased it to 200 but not yet updated our docs. 

How many MMSIs are you looking to support ? We can likely raise it to ~5000 or higher but do want to put an upper bound on the maximum number so that an subscription can not just send say a GB of MMSIs and use all the memory of the machine.

**Comment by MartinElvar** [comment]
Aah that make sense. 200 will do for now, and if 5000 is possible at some point, i'm gonna roll with my solution where i rely on your filtering. :+1: 

Bonus question: Currently i'm only filtering on a few MMSI, but the connection seems to get terminated from time to time, i think due to it being idle. Do you disconnect sockets if not messages have passed through the wire for x amount of time? If that is the case i guess i should just reconnect, but it could however mean lost messages.

**Comment by aisstream** [comment]
Likely not from being idle as we do not drop idle connections . As you are aware, there is a whole host of reasons the connection can be dropped. For example connections are dropped if the node you are connected through goes through a new deployment, if there is a networking connection issues, and even sometimes by the client you are using.

**Comment by MartinElvar** [comment]
Great, thank you. I'll make sure to reach out, if and when 200 becomes a problem. :+1:
